domain: a-chacon.com
url: https://a-chacon.com

title: a-chacon
email: andres.ch@protonmail.com
description: >-
  Personal website of Andrés. Ruby developer. Backend. Based in Chile.

defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true
