domain: a-chacon.com
url: https://a-chacon.com

title: a-chacon
email: andres.ch@protonmail.com
description: >-
  This is the andre's personal web site.


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
