domain: a-chacon.com
url: https://a-chacon.com

title: a-chacon
email: andres.ch@protonmail.com

defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-polyglot

languages: ["en", "es"]
default_lang: "es"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

words: ["Rails", "Ruby", "Python", "AWS"]
